_wandb:
    value:
        cli_version: 0.19.2
        code_path: code/train_siso.py
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 35
                - 55
            "4": 3.12.3
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
env_name:
    value: RL Variable Reference
policy_type:
    value: MlpPolicy
total_timesteps:
    value: 500000
